window:
  padding:
    x: 0
    y: 0

tabspaces: 4

font:
  normal:
    family: IBM Plex Mono
    style: Text
  bold:
    family: IBM Plex Mono
    #style: Bold
  italic:
    family: IBM Plex Mono
    style: Text Italic

  {%@@ if profile == "wintermute" @@%}
  size: 9.0
  {%@@ else @@%}
  size: 13.0
  {%@@ endif @@%}

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: -2

# Base16 Gruvbox dark, soft - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x32302f'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x32302f'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x32302f'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

mouse:
  url:
    launcher: xdg-open
