config:
  backup: true
  banner: false
  create: true
  dotpath: .
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop

dotfiles:
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
    link: link_children
  d_fontconfig:
    dst: ~/.config/fontconfig
    src: config/fontconfig
  d_htop:
    dst: ~/.config/htop
    src: config/htop
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_sway:
    dst: ~/.config/sway
    src: config/sway
  d_kak:
    dst: ~/.config/kak
    link: link_children
    src: config/kak
  d_kaklsp:
    dst: ~/.config/kak-lsp
    src: config/kak-lsp
  d_konsole:
    dst: ~/.local/share/konsole
    src: local/share/konsole
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_vifm:
    dst: ~/.config/vifm
    link: link_children
    src: config/vifm
  d_mako:
    dst: ~/.config/mako
    src: config/mako
  d_mpv:
    dst: ~/.config/mpv
    src: config/mpv
  d_zsh:
    dst: ~/.zsh
    src: zsh
    link: link_children
  f_alacritty.yml:
    dst: ~/.config/alacritty/alacritty.yml
    src: config/alacritty/alacritty.yml
  f_aria2.conf:
    dst: ~/.config/aria2/aria2.conf
    src: config/aria2/aria2.conf
  f_git:
    dst: ~/.config/git/config
    src: config/git/config
  f_dircolors:
    dst: ~/.dircolors
    src: dircolors
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_latexmkrc:
    dst: ~/.latexmkrc
    src: latexmkrc
  f_makepkg.conf:
    dst: ~/.config/pacman/makepkg.conf
    src: config/pacman/makepkg.conf
  f_profiles.clj:
    dst: ~/.lein/profiles.clj
    src: lein/profiles.clj
  f_redshift.conf:
    dst: ~/.config/redshift.conf
    src: config/redshift.conf
  f_ssh:
    dst: ~/.ssh/config
    src: ssh/config
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zathurarc:
    dst: ~/.config/zathura/zathurarc
    src: config/zathura/zathurarc
  f_pam_env:
    dst: ~/.pam_environment
    src: pam_environment
  f_cargo_config:
    src: cargo/config
    dst: ~/.cargo/config
  d_juliaconfig:
    src: julia/config
    dst: ~/.julia/config
  d_yay:
    src: config/yay
    dst: ~/.config/yay
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  d_oomox:
    src: config/oomox
    dst: ~/.config/oomox

dynvariables:
  hostname: "hostname -s"

profiles:
  desktop:
    dotfiles:
    - ALL

  server:
    dotfiles:
      - d_nvim
      - d_htop
      - d_kak
      - d_kaklsp
      - d_ranger
      - d_vifm
      - d_zsh
      - f_git
      - f_dircolors
      - f_latexmkrc
      - f_makepkg.conf
      - f_profiles.clj
      - f_ssh
      - f_tmux.conf
      - f_pam_env
      - f_cargo_config
      - d_juliaconfig
      - d_yay
