source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "andreyorst/smarttab.kak" config %{
    set-option global softtabstop 4
}

plug "andreyorst/fzf.kak" config %{
    map global user f ': fzf-mode<ret>' -docstring 'fzf mode'
} defer "fzf" %{
    set-option global fzf_implementation 'sk'
    set-option global fzf_file_command 'rg'
    set-option global fzf_highlight-command 'bat'
}

plug "danr/kakoune-easymotion" config %{
    map global user e ': enter-user-mode easymotion<ret>' -docstring 'easymotion commands'
}

hook global WinCreate ^[^*]+$ %{editorconfig-load}
hook global BufCreate ^[^*]+$ expandtab

set-option global ui_options ncurses_assistant=none
set-option global tabstop 4
set-option global scrolloff 3,0

colorscheme gruvbox

map global normal '#'        '<space>:comment-line<ret>' -docstring 'comment line'
map global normal '='        '|par 80<ret>'              -docstring 'Format with par(1)'
map global normal '<plus>'   '<a-|>wl-copy<ret>'         -docstring 'Pipe to clipboard'
map global normal '<a-plus>' '!wl-paste<ret>'            -docstring 'Pipe from clipboard'

map global normal '/'     '/(?i)'     -docstring 'case insensitive search' 
map global normal '<a-/>' '<a-/>(?i)' -docstring 'case insensitive backward search' 
map global normal '?'     '?(?i)'     -docstring 'case insensitive extend search' 
map global normal '<a-?>' '<a-?>(?i)' -docstring 'case insensitive backward extend-search' 

map global normal 'n' 'nvv'
map global normal 'ü' '<a-;>'
map global normal 'ö' '<a-:>'
map global normal 'ä' '<a-S>'
map global normal '<minus>' 'x_c'

map global user l ': enter-user-mode lsp<ret>' -docstring 'Language Server commands'

add-highlighter global/ number-lines
add-highlighter global/ wrap

set-face global Information rgb:a89984,rgb:3c3836

define-command -docstring %{x11-repl [<arguments>]: create a new window for repl interaction
All optional parameters are forwarded to the new window} \
    -override \
    -params .. \
    -shell-completion \
    x11-repl %{ evaluate-commands %sh{
        if [ $# -eq 0 ]; then cmd="${SHELL:-sh}"; else cmd="$@"; fi
        setsid alacritty -t kak_repl_window -e sh -c ${cmd} < /dev/null > /dev/null 2>&1 &
}}

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|julia|r) %{
        lsp-enable-window
}
